services:
  udv.web:
    image: udv.web
    build:
      context: .
      dockerfile: Udv.Web/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "DB_HOST=host=db;Database=udv;Port=5432;User Id=postgres;Password=postgres"
      - "ACCESS_TOKEN="
    depends_on:
      - db
    networks:
      - my-network
    
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "udv"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network

volumes:
  pgdata:

networks:
  my-network:
    driver: bridge